[book]
authors = ["Ryan"]
language = "en"
multilingual = false
src = "src"
title = "Git Ventures"
[preprocessor]
[preprocessor.toc]
command = "mdbook-toc"
[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]
[preprocessor.plantuml]
plantuml-cmd="plantuml"
[output]
# [output.latex]
# latex    = true  # default = true
# pdf      = true  # default = false
# markdown = true  # default = false
[output.html]
additional-css =["mermaid.css"]
additional-js =["mermaid.min.js", "mermaid-init.js"]